# Generated by Django 3.0.7 on 2020-06-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('r_date', models.CharField(blank=True, max_length=20, null=True)),
                ('v_date', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('occup', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'occupation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('zipcode', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='search.User')),
                ('rating', models.IntegerField()),
                ('timestamp', models.IntegerField()),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenreMovie',
            fields=[
                ('gid', models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='search.Genre')),
            ],
            options={
                'db_table': 'genre_movie',
                'managed': False,
            },
        ),
    ]
