# Generated by Django 3.0.7 on 2020-06-28 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Occupation',
        ),
    ]
